### ISSUE TITLE
Poet image doesn't retain aspect ratio

### ISSUE THREAD

**Issue by toiletdragon** [jordankettles/345-group-project#21]
The poet image is stretched to fill the ImageView in both axis. It should be scaled so its largest axis matches the view while retaining its original aspect ratio (it should follow the behaviour of android:scaleType="fitStart").

**Comment by mf284** [comment]
Resolved by inserting drawable instead of background. 
884abca3a97538d87308d8decc932f89b869aab4

**Comment by mf284** [comment]
![image](https://user-images.githubusercontent.com/80860811/129333368-c4d2b14e-a653-480c-b984-efa5fed987f0.png)
