### ISSUE TITLE
Bad word filter rejects "Knight"

### ISSUE THREAD

**Issue by mf284** [jordankettles/345-group-project#28]
Happens with "He was a dark and stormy knight" and "knight" on their own. 
I suspect this is because of substring(1,4) of "knight".

**Comment by jordankettles** [comment]
I see. I can make a fix that ensures there is a space before or a space after each banned word.

**Comment by jordankettles** [comment]
Wrote that fix

**Comment by jordankettles** [comment]
Commit is called Fix bad-word filter 5858bcc40c4f70e40ceea709e3a61ac819239c01
